/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashwini K. Singh
 */
public class OS_Billing_window extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    String qry1,qry="select * from bill_items;";

    /**
     * Creates new form ztext123
     */
    public OS_Billing_window() {
        initComponents();
        try{
            Class.forName("java.sql.DriverManager");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000");
            stmt = (Statement)con.createStatement(rs.TYPE_FORWARD_ONLY,rs.CONCUR_UPDATABLE);
            rs=stmt.executeQuery(qry);
         }
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane,e.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisplay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listToy = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIcode = new javax.swing.JLabel();
        lblIName = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblTqty = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtOrdQty = new javax.swing.JTextField();
        chkBuy = new javax.swing.JCheckBox();
        btnCnfOrd = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblDiscountP = new javax.swing.JLabel();
        lblTotAmt = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblTotPayAmt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDisplay.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        btnDisplay.setText("Display   Products in Bag");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 530, 39));

        btnCancel.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 120, 30));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select products below");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("to see its details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 91, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITEMS ORDERED", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Brand", "Type", "Price", "Qty Ordered", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tbOrder);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 700, -1));

        listToy.setModel(new DefaultListModel());
        listToy.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listToy.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listToyValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listToy);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 156, 198));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Item Code");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Item Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Brand");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Price");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Type");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Qty in Stock");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Order Qty");

        lblIcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOrdQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        chkBuy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkBuy.setText("CLICK ME IF you want to buy this item");
        chkBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBuyActionPerformed(evt);
            }
        });

        btnCnfOrd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCnfOrd.setText("Confirm Order");
        btnCnfOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnfOrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(lblIName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblIcode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(27, 27, 27)
                                .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(54, 54, 54)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkBuy))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOrdQty, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCnfOrd)
                .addGap(181, 181, 181))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(lblIcode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblIName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblTqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtOrdQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkBuy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCnfOrd)
                        .addGap(779, 779, 779))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 520, 250));

        jLabel17.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("User Type");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 90, -1));

        jLabel18.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Payable Amount (Rs.)");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        jLabel19.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total Amount (Rs.)");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        jLabel20.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Discount ( % )");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 110, -1));

        jLabel21.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Discount Amt (Rs.)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 150, 30));

        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 160, 30));

        lblDiscountP.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscountP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscountP.setText("0");
        lblDiscountP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblDiscountP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 160, 30));

        lblTotAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblTotAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotAmt.setText("0");
        lblTotAmt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblTotAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 160, 30));

        lblDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscount.setText("0");
        lblDiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 160, 30));

        lblTotPayAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblTotPayAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotPayAmt.setText("0");
        lblTotPayAmt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(lblTotPayAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)aaa6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void emptyList(){
     DefaultListModel model=(DefaultListModel)listToy.getModel();
     while(model.getSize()>0)
         model.remove(0); } 

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Thank you for using the Online Shopping application");
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        emptyList();
        int count=0;
        String query="select Item_name from bill_items;";
        DefaultListModel model=(DefaultListModel)listToy.getModel();
        try
        {
            Class.forName("java.sql.DriverManager");
            con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000"); 
            stmt = (Statement) con.createStatement(); 
            rs =stmt.executeQuery(query);
            while(rs.next())
            {
              model.add(count,rs.getString("Item_name"));
              count++;
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        txtOrdQty.setEnabled(false);
        //new connection coding
        String ut = null;
        String qy="select * from curr_login;";
        try{
            Class.forName("java.sql.Driver");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt=(Statement)con.createStatement();
            rs = stmt.executeQuery(qy);
            while(rs.next())
            {
              ut=rs.getString("User_type");
            }
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        lblUserType.setText(ut);
        if (ut.equals("Premium"))
            lblDiscountP.setText("20");
        else
            lblDiscountP.setText("5");
        btnDisplay.setEnabled(false);
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)tbOrder.getModel();
        int count=model.getRowCount();
        String total=lblTotPayAmt.getText();
        String disAmt=lblDiscount.getText();
        String totAmt=lblTotAmt.getText();
        int sno;
        String fn = null,ln = null,em = null,ut = null,addr = null;
        String query="select * from curr_login" ;
        try
        {
            Class.forName("java.sql.DriverManager");
            con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000"); 
            stmt = (Statement) con.createStatement(); 
            rs =stmt.executeQuery(query);
            while(rs.next())
            {
                sno=rs.getInt(1);
                fn=rs.getString(2);
                ln=rs.getString(3);
                em=rs.getString(4);
                ut=rs.getString(6);
                addr=rs.getString(7);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        if(totAmt.equals("0"))
            JOptionPane.showMessageDialog(rootPane,"No item ordered !!!");
        else
        {
        JOptionPane.showMessageDialog(rootPane,"Dear Mr. "+fn+" "+ln
        +",\nYou have ordered for "+count+" items and your payable bill amount is Rs."+total+"\n"
        +"Being a "+ut+" user , you got a discount of Rs. "+disAmt+"\n\n"        
        +"Your shipment will reach to your address: "+addr+" within 7-10 days."
        +"\nThe bill has been sent to your E-mail address: "+em);
        
        int n=0;
        try{
            Class.forName("java.sql.DriverManager");
            con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000"); 
            stmt = (Statement) con.createStatement();
            rs=stmt.executeQuery("select * from transactions;");
            while (rs.last()){
            n = rs.getInt("txn_no");
            rs.close();
            stmt.close();
            con.close();
            }
        }
        catch (Exception e)
       {
           System.out.println(e.getMessage());
       }
        
        n=n+1;
        String un=fn+" "+ln;
        String qy1="insert into transactions values("+n+",'"+un+"','"+em+"','"+totAmt+"','"+disAmt+"','"+total+"',"+"(select sysdate()));";
        System.out.println(qy1);
        try
        {
            Class.forName("java.sql.DriverManager");
            con =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000"); 
            stmt = (Statement) con.createStatement(); 
            int a=stmt.executeUpdate(qy1);
            JOptionPane.showMessageDialog(rootPane,"Transaction completed successfully .");
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        btnSubmit.setEnabled(false);
        btnCnfOrd.setEnabled(false);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void listToyValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listToyValueChanged
        // TODO add your handling code here:
        
        chkBuy.setSelected(false);
        String selVal=(String)listToy.getSelectedValue();
        String query="select * from Bill_items where Item_name='"+ selVal +"';";
        try{
            Class.forName("java.sql.Driver");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt=(Statement)con.createStatement();
            rs = stmt.executeQuery(query);
            rs.next();
            {
                lblIcode.setText(""+rs.getInt(1));
                lblType.setText(rs.getString(2));
                lblBrand.setText(rs.getString(3));
                lblIName.setText(rs.getString(4));
                lblPrice.setText(""+rs.getFloat(5));
                lblTqty.setText(""+rs.getInt(6));
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        chkBuy.setSelected(false);
    }//GEN-LAST:event_listToyValueChanged

    private void chkBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBuyActionPerformed
        // TODO add your handling code here:
        if(chkBuy.isSelected())
        txtOrdQty.setEnabled(true);
        else txtOrdQty.setEnabled(false);
    }//GEN-LAST:event_chkBuyActionPerformed

    private void btnCnfOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnfOrdActionPerformed
        // TODO add your handling code here:
        int qtyA=Integer.parseInt(lblTqty.getText());
        int qtyO=Integer.parseInt(txtOrdQty.getText());
        if(chkBuy.isSelected()==false)
            JOptionPane.showMessageDialog(rootPane,"Please select order quantity");
        else if(qtyO<=0)
            JOptionPane.showMessageDialog(rootPane,"Order quantity must not be less than 1 !!!");
        else if(qtyO>qtyA)
        JOptionPane.showMessageDialog(rootPane,"Only "+ qtyA+" items of Item Code "+ lblIcode.getText()+" are in stock! \n SORRY, Cannot take your order.");
        else{
            float amt=qtyO*(Float.parseFloat(lblPrice.getText()));
            float total=Float.parseFloat(lblTotAmt.getText());
            DefaultTableModel model=(DefaultTableModel)tbOrder.getModel();
            int tc=Integer.parseInt(lblIcode.getText());
            qry="UPDATE Bill_items SET stock=stock-"+qtyO+" where Item_code="+tc+";";
            qry1="UPDATE Products SET stock=stock-"+qtyO+" where Item_code="+tc+";";
            try
            {
                Class.forName("java.sql.DriverManager");
                con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineshopping", "root","0000");
                stmt =(Statement)con.createStatement(rs.TYPE_FORWARD_ONLY,rs.CONCUR_UPDATABLE);
                stmt.executeUpdate(qry);
                stmt.executeUpdate(qry1);
                //now adding to order table
                model.addRow(new Object[]{
                lblIcode.getText(),lblIName.getText(),lblBrand.getText(),lblType.getText(),lblPrice.getText(),txtOrdQty.getText(),amt });
            total=total+amt;
            lblTotAmt.setText(""+total);
        Float disP,disAmt,totPayAmt;
        Float totAmt=Float.parseFloat(lblTotAmt.getText());
        disP=Float.parseFloat(lblDiscountP.getText());
        disAmt=totAmt*disP/100;
        totPayAmt=totAmt-disAmt;
        lblDiscount.setText(""+disAmt);
        lblTotPayAmt.setText(""+totPayAmt);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        txtOrdQty.setText("");
        txtOrdQty.setEnabled(false);
        chkBuy.setSelected(false);
        }
    }//GEN-LAST:event_btnCnfOrdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Billing_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Billing_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Billing_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Billing_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OS_Billing_window().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCnfOrd;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountP;
    private javax.swing.JLabel lblIName;
    private javax.swing.JLabel lblIcode;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTotAmt;
    private javax.swing.JLabel lblTotPayAmt;
    private javax.swing.JLabel lblTqty;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JList<String> listToy;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTextField txtOrdQty;
    // End of variables declaration//GEN-END:variables
}
