/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author manjeet
 */
public class OS_Menz_Shirt extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode, p,s;
String bname, iname, t;
    /**
     * Creates new form shirts_m
     */
    public OS_Menz_Shirt() {
        initComponents();
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        
        
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddToBag2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddToBag1 = new javax.swing.JButton();
        RemoveFromeBag1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddToBag3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddToBag4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AddToBag5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddToBag6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddToBag7 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        AddToBag8 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        AddToBag9 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        GoToBillingSection = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 710));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)windsor checked shirt.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        AddToBag2.setText("Add to Bag");
        AddToBag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove from bag");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MADDISON STRIPPED SHIRT - TOMMY HILFIGER");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)thomas E fit.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        AddToBag1.setText("Add to Bag");
        AddToBag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag1ActionPerformed(evt);
            }
        });

        RemoveFromeBag1.setText("Remove from bag");
        RemoveFromeBag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFromeBag1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THOMAS E FIT - TOMMY HILFIGER");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)oliver checked shirt.jpg"))); // NOI18N

        AddToBag3.setText("Add to Bag");
        AddToBag3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag3ActionPerformed(evt);
            }
        });

        jButton7.setText("Remove from bag");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WINDSOR CHECKED SHIRT - TOMMY HILFIGER");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)madison striped shirt.jpg"))); // NOI18N

        AddToBag4.setText("Add to Bag");
        AddToBag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag4ActionPerformed(evt);
            }
        });

        jButton9.setText("Remove from bag");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PACIFIC S - DIESEL");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Smash-RS shirt.jpg"))); // NOI18N

        AddToBag5.setText("Add to Bag");
        AddToBag5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag5ActionPerformed(evt);
            }
        });

        jButton11.setText("Remove from bag");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("OLIVER CHECKED SHIRT - TOMMY HILFIGER");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Sermon-R shirt.jpg"))); // NOI18N

        AddToBag6.setText("Add to Bag");
        AddToBag6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag6ActionPerformed(evt);
            }
        });

        jButton13.setText("Remove from bag");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SMASH R - DIESEL");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Pacific-S shirt.jpg"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SERMON R - DIESEL");

        AddToBag7.setText("Add to Bag");
        AddToBag7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag7ActionPerformed(evt);
            }
        });

        jButton17.setText("Remove from bag");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PRICE :  Rs 11,400");

        jLabel40.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("PRICE : Rs 9,596 ");

        jLabel41.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("PRICE :  Rs 9,876");

        jLabel42.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("PRICE : Rs 10,758 ");

        jLabel43.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("PRICE :  Rs 7,045");

        jLabel44.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("PRICE : Rs 8,600 ");

        jLabel45.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("PRICE : Rs 11,023    ");

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("SHIRTS");
        jLabel59.setOpaque(true);

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("T- SHIRTS");
        jLabel60.setOpaque(true);

        jLabel61.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("PRICE :  Rs 2,790");

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)tommy regular fit t-shirt.jpg"))); // NOI18N

        AddToBag8.setText("Add to Bag");
        AddToBag8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag8ActionPerformed(evt);
            }
        });

        jButton41.setText("Remove from bag");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jLabel63.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("REGULAR FIT T-SHIRT - TOMMY HILFIGER");

        jLabel67.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("PRICE :  Rs 3,500");

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)property regular fir t-shirt.jpg"))); // NOI18N

        jLabel69.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("PROPERTY REGULAR FIT - TOMMY HILFIGER");

        jButton44.setText("Remove from bag");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        AddToBag9.setText("Add to Bag");
        AddToBag9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBag9ActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("PRICE :  Rs 3,859");

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)base regular fit t-shirt.jpg"))); // NOI18N

        jLabel75.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("BASE T-SHIRT - TOMMY HILFIGER");

        jButton48.setText("Remove from bag");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        jButton49.setText("Add to Bag");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("PRICE :  Rs 3,377");

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Three-T.jpg"))); // NOI18N

        jLabel78.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("TITLE - DIESEL");

        jButton50.setText("Remove from bag");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });

        jButton51.setText("Add to Bag");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("PRICE :  Rs 4,309");

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Oneself-T.jpg"))); // NOI18N

        jLabel81.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("ONESELF - DIESEL");

        jButton52.setText("Remove from bag");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });

        jButton53.setText("Add to Bag");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("PRICE :  RS 3,807");

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Kali-T.jpg"))); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("KADI - DIESEL");

        jButton54.setText("Remove from bag");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });

        jButton55.setText("Add to Bag");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("PRICE :  Rs 4,600");

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Globic-T.jpg"))); // NOI18N

        jLabel90.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("GLOBIC T - DIESEL");

        jButton58.setText("Remove from bag");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });

        jButton59.setText("Add to Bag");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(AddToBag8)
                        .addGap(65, 65, 65)
                        .addComponent(jButton41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton51)
                                        .addGap(65, 65, 65)
                                        .addComponent(jButton50))
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel76)
                                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel67))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddToBag9)
                                .addGap(65, 65, 65)
                                .addComponent(jButton44)))
                        .addGap(119, 119, 119))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(AddToBag2)
                                .addGap(51, 51, 51)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel42)
                        .addGap(333, 333, 333))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(551, 551, 551)
                                    .addComponent(jLabel11))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(AddToBag3)
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton7))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddToBag4)
                                .addGap(45, 45, 45)
                                .addComponent(jButton9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddToBag6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddToBag5)
                                .addGap(45, 45, 45)
                                .addComponent(jButton11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton53)
                .addGap(65, 65, 65)
                .addComponent(jButton52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton55)
                .addGap(28, 28, 28)
                .addComponent(jButton54)
                .addGap(148, 148, 148))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel82)
                .addGap(257, 257, 257))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jButton59)
                                            .addGap(28, 28, 28)
                                            .addComponent(jButton58))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel89))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel88)))
                                    .addGap(67, 67, 67)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton49)
                                .addGap(65, 65, 65)
                                .addComponent(jButton48))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(AddToBag1)
                        .addGap(45, 45, 45)
                        .addComponent(RemoveFromeBag1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(AddToBag7)
                        .addGap(65, 65, 65)
                        .addComponent(jButton17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel59)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddToBag1)
                    .addComponent(RemoveFromeBag1)
                    .addComponent(AddToBag2)
                    .addComponent(jButton3))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddToBag3)
                    .addComponent(jButton7)
                    .addComponent(AddToBag4)
                    .addComponent(jButton9))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddToBag5)
                    .addComponent(jButton11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13)
                        .addComponent(AddToBag6)))
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddToBag7)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel60)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel67)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddToBag9)
                            .addComponent(jButton44)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddToBag8)
                            .addComponent(jButton41))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel76))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton51)
                    .addComponent(jButton50)
                    .addComponent(jButton49)
                    .addComponent(jButton48))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(jLabel82))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton52)
                        .addComponent(jButton54)
                        .addComponent(jButton55)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel88)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton58)
                    .addComponent(jButton59))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 920, 610);

        GoToBillingSection.setBackground(new java.awt.Color(0, 0, 0));
        GoToBillingSection.setForeground(new java.awt.Color(204, 204, 204));
        GoToBillingSection.setText("Go To Billing Section");
        GoToBillingSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoToBillingSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToBillingSectionActionPerformed(evt);
            }
        });
        getContentPane().add(GoToBillingSection);
        GoToBillingSection.setBounds(770, 10, 180, 50);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)36.jpg"))); // NOI18N
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1010, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToBag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag1ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1090;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
            System.out.println(""+icode+p+bname+iname+t+s);
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag1ActionPerformed

    private void AddToBag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag2ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1091;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag2ActionPerformed

    private void AddToBag3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag3ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1092;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag3ActionPerformed

    private void AddToBag4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag4ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1093;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag4ActionPerformed

    private void AddToBag6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag6ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1095;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag6ActionPerformed

    private void AddToBag5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag5ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1094;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag5ActionPerformed

    private void AddToBag7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag7ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1096;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag7ActionPerformed

    private void AddToBag8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag8ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1097;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag8ActionPerformed

    private void AddToBag9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBag9ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1098;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_AddToBag9ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1099;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1100;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1101;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1102;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1103;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p + "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton59ActionPerformed

    private void RemoveFromeBag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFromeBag1ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1090;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_RemoveFromeBag1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1091;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1092;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1093;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1094;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1095;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1096;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1097;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1098;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1099;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1100;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1101;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1102;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1103;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton58ActionPerformed

    private void GoToBillingSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToBillingSectionActionPerformed
        // TODO add your handling code here:
        new OS_Billing_window().setVisible(true);
    }//GEN-LAST:event_GoToBillingSectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Shirt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Shirt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Shirt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Shirt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OS_Menz_Shirt().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToBag1;
    private javax.swing.JButton AddToBag2;
    private javax.swing.JButton AddToBag3;
    private javax.swing.JButton AddToBag4;
    private javax.swing.JButton AddToBag5;
    private javax.swing.JButton AddToBag6;
    private javax.swing.JButton AddToBag7;
    private javax.swing.JButton AddToBag8;
    private javax.swing.JButton AddToBag9;
    private javax.swing.JButton GoToBillingSection;
    private javax.swing.JButton RemoveFromeBag1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
