/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author manjeet
 */
public class OS_Menz_Accessories extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode,p,s;
String bname, iname, t;
    /**
     * Creates new form accessories_m
     */
    public OS_Menz_Accessories() {
        initComponents();
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton59 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 570));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(dg)Buckle belt.jpg"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(dg)leather wallet.jpg"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Alisi.jpg"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Askio-Neck.jpg"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Bedeca.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Cristar.jpg"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)DM012.jpg"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)DM029.jpg"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)Hi-Jack.jpg"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)ZR016.jpg"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(di)K-Jemio.jpg"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)Boston leather belt.jpg"))); // NOI18N

        jButton59.setBackground(new java.awt.Color(0, 153, 153));
        jButton59.setText("Add to Bag");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });

        jButton58.setBackground(new java.awt.Color(0, 153, 153));
        jButton58.setText("Remove from bag");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(51, 51, 51));
        jLabel88.setText("PRICE :  Rs 5,498");

        jLabel90.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(51, 51, 51));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("PURPLE BLACK SHADES - DIESEL");

        jLabel89.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(51, 51, 51));
        jLabel89.setText("PRICE :  Rs 25,650");

        jLabel91.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(51, 51, 51));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("HI JACK - DIESEL");

        jButton60.setBackground(new java.awt.Color(0, 153, 153));
        jButton60.setText("Add to Bag");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });

        jButton61.setBackground(new java.awt.Color(0, 153, 153));
        jButton61.setText("Remove from bag");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });

        jLabel92.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(51, 51, 51));
        jLabel92.setText("PRICE :  Rs 3,200");

        jLabel93.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(51, 51, 51));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("WINTER CAP- DIESEL");

        jButton62.setBackground(new java.awt.Color(0, 153, 153));
        jButton62.setText("Add to Bag");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });

        jButton63.setBackground(new java.awt.Color(0, 153, 153));
        jButton63.setText("Remove from bag");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });

        jLabel94.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(51, 51, 51));
        jLabel94.setText("PRICE :  Rs 7,389");

        jLabel95.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(51, 51, 51));
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("SMART WRISTWATCH - DIESEL");

        jButton64.setBackground(new java.awt.Color(0, 153, 153));
        jButton64.setText("Add to Bag");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });

        jButton65.setBackground(new java.awt.Color(0, 153, 153));
        jButton65.setText("Remove from bag");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(51, 51, 51));
        jLabel96.setText("PRICE :  Rs 5,089");

        jLabel97.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(51, 51, 51));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("GREEN SHADES - DIESEL");

        jButton66.setBackground(new java.awt.Color(0, 153, 153));
        jButton66.setText("Add to Bag");
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });

        jButton67.setBackground(new java.awt.Color(0, 153, 153));
        jButton67.setText("Remove from bag");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });

        jLabel98.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(51, 51, 51));
        jLabel98.setText("PRICE :  Rs 4,278");

        jLabel99.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(51, 51, 51));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("GREY STRAW HAT - DIESEL");

        jButton68.setBackground(new java.awt.Color(0, 153, 153));
        jButton68.setText("Add to Bag");
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });

        jButton69.setBackground(new java.awt.Color(0, 153, 153));
        jButton69.setText("Remove from bag");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });

        jButton70.setBackground(new java.awt.Color(0, 153, 153));
        jButton70.setText("Remove from bag");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });

        jLabel100.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(51, 51, 51));
        jLabel100.setText("PRICE :  Rs 1,208");

        jLabel101.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(51, 51, 51));
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("NECK CHAIN - DIESEL");

        jButton71.setBackground(new java.awt.Color(0, 153, 153));
        jButton71.setText("Add to Bag");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });

        jButton72.setBackground(new java.awt.Color(0, 153, 153));
        jButton72.setText("Remove from bag");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });

        jLabel102.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(51, 51, 51));
        jLabel102.setText("PRICE :  Rs 3,908");

        jLabel103.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(51, 51, 51));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("BOSTON LEATHER BELT - TOMMY HILFIGER");

        jButton73.setBackground(new java.awt.Color(0, 153, 153));
        jButton73.setText("Add to Bag");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });

        jButton74.setBackground(new java.awt.Color(0, 153, 153));
        jButton74.setText("Remove from bag");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });

        jLabel104.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(51, 51, 51));
        jLabel104.setText("PRICE :  Rs 4,765");

        jLabel105.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(51, 51, 51));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("SILVER BELT -  DIESEL");

        jButton75.setBackground(new java.awt.Color(0, 153, 153));
        jButton75.setText("Add to Bag");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });

        jButton76.setBackground(new java.awt.Color(0, 153, 153));
        jButton76.setText("Remove from bag");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });

        jLabel106.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(51, 51, 51));
        jLabel106.setText("PRICE :  Rs 1,867");

        jLabel107.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(51, 51, 51));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("METAL BRACELET -  DIESEL");

        jButton77.setBackground(new java.awt.Color(0, 153, 153));
        jButton77.setText("Add to Bag");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });

        jButton78.setBackground(new java.awt.Color(0, 153, 153));
        jButton78.setText("Remove from bag");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });

        jLabel108.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(51, 51, 51));
        jLabel108.setText("PRICE :  Rs 3,000");

        jLabel109.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(51, 51, 51));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("BUCKLE BELT - DOLCE & GABBANA");

        jButton79.setBackground(new java.awt.Color(0, 153, 153));
        jButton79.setText("Add to Bag");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });

        jButton80.setBackground(new java.awt.Color(0, 153, 153));
        jButton80.setText("Remove from bag");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });

        jLabel110.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(51, 51, 51));
        jLabel110.setText("PRICE :  Rs 4,600");

        jLabel111.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(51, 51, 51));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("LEATHER WALLET - DOLCE & GABBANA");

        jButton81.setBackground(new java.awt.Color(0, 153, 153));
        jButton81.setText("Add to Bag");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });

        jButton82.setBackground(new java.awt.Color(0, 153, 153));
        jButton82.setText("Add to Bag");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });

        jButton83.setBackground(new java.awt.Color(0, 153, 153));
        jButton83.setText("Remove from bag");
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });

        jLabel112.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(51, 51, 51));
        jLabel112.setText("PRICE :  Rs 29,509");

        jLabel113.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(51, 51, 51));
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("DAVID MESSENGER - TOMMY HILFIGER");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)David messenger.jpg"))); // NOI18N

        jButton84.setBackground(new java.awt.Color(0, 153, 153));
        jButton84.setText("Add to Bag");
        jButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton84ActionPerformed(evt);
            }
        });

        jButton85.setBackground(new java.awt.Color(0, 153, 153));
        jButton85.setText("Remove from bag");
        jButton85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton85ActionPerformed(evt);
            }
        });

        jLabel114.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(51, 51, 51));
        jLabel114.setText("PRICE :  Rs 4,090");

        jLabel115.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(51, 51, 51));
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel115.setText("BRISK SUNGLASSES - TOMMY HILFIGER");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th) TH 1091-s sunglasses.jpg"))); // NOI18N

        jButton86.setBackground(new java.awt.Color(0, 153, 153));
        jButton86.setText("Add to Bag");
        jButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton86ActionPerformed(evt);
            }
        });

        jButton87.setBackground(new java.awt.Color(0, 153, 153));
        jButton87.setText("Remove from bag");
        jButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton87ActionPerformed(evt);
            }
        });

        jLabel116.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(51, 51, 51));
        jLabel116.setText("PRICE :  Rs 15,650");

        jLabel117.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(51, 51, 51));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("HARRISON WATCH - TOMMY HILFIGER");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)harrison watch.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel88)
                                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton59)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButton58))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel100)
                                    .addGap(121, 121, 121))
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton71)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButton70))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel98)
                                    .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton68)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton69))
                                    .addComponent(jLabel110)
                                    .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton81)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton80))
                                    .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel112)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton82)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton83)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                                .addComponent(jButton61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton84)
                                                .addComponent(jLabel114))
                                            .addGap(35, 35, 35)
                                            .addComponent(jButton85)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10)))))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton86)
                                .addGap(28, 28, 28)
                                .addComponent(jButton87))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel116)
                                .addGap(138, 138, 138))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel96)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton66)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton67))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel108)
                                                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButton79)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jButton78)))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel102)
                                                    .addComponent(jButton73))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton72)))))
                                .addGap(203, 203, 203))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton60)
                                    .addComponent(jLabel89))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel92)
                            .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton62)
                                .addGap(28, 28, 28)
                                .addComponent(jButton63))
                            .addComponent(jLabel94)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton64)
                                .addGap(28, 28, 28)
                                .addComponent(jButton65))
                            .addComponent(jLabel104)
                            .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton75)
                                .addGap(28, 28, 28)
                                .addComponent(jButton74))
                            .addComponent(jLabel106)
                            .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton77)
                                .addGap(28, 28, 28)
                                .addComponent(jButton76)))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel106)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton76)
                            .addComponent(jButton77)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel108)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton78)
                            .addComponent(jButton79)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel110)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton80)
                            .addComponent(jButton81))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel104)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton74)
                                            .addComponent(jButton75)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel102)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton72)
                                            .addComponent(jButton73)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel100)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton70)
                                            .addComponent(jButton71))))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel94)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton65)
                                    .addComponent(jButton64)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel98)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton69)
                                    .addComponent(jButton68)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel96)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton67)
                            .addComponent(jButton66))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel88)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton58)
                            .addComponent(jButton59)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel89)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton61)
                            .addComponent(jButton60)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel92)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton63)
                            .addComponent(jButton62))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel112))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel114)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton83)
                            .addComponent(jButton82)
                            .addComponent(jButton85)
                            .addComponent(jButton84)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel116)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton87)
                            .addComponent(jButton86))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 1180, 450);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go To Billing Section");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1010, 10, 180, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)36.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1250, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1104;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton81ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1105;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1106;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1107;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1108;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1109;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1110;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1111;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1112;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1113;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1114;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1115;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1116;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton82ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1117;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton84ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1118;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton86ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new OS_Billing_window().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1104;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1105;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1106;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1107;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1108;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1109;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1110;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1111;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1112;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1113;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1114;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1115;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1116;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jButton85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton85ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1117;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton85ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1118;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton87ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OS_Menz_Accessories().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
