/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author manjeet
 */
public class OS_Menz_Jeans extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode, p,s;
String bname, iname, t;
    /**
     * Creates new form jeans_m
     */
    public OS_Menz_Jeans() {
        initComponents();
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 770));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(af) A&F super skinny jeans.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(af) A&F vintage white wash.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("A&F VINTAGE WHITE WASH - ABERCROMBIE & FITCH");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("A&F SUPER SKINNY JEANS - ABERCROMBIE & FITCH");

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("ADD TO BAG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setText("REMOVE FROM BAG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("PRICE : Rs 5,202");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("PRICE : Rs 4,309");

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setText("REMOVE FROM BAG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setText("ADD TO BAG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("PRICE : Rs 5,798");

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setText("REMOVE FROM BAG");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("A&F DESTROYED VINTAGE DARK - ABERCROMBIE & FITCH");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(af)A&F destroyed vintage dark wash.jpg"))); // NOI18N
        jLabel9.setText("jLabel2");

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("ADD TO BAG");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("A&F VINTAGE SKINY WHITE - ABERCROMBIE & FITCH");

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setText("REMOVE FROM BAG");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 102));
        jButton8.setText("ADD TO BAG");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(af)A&F vintage skinny white.jpg"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("PRICE : Rs 5,809");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("PRICE : Rs 6,495");

        jButton9.setBackground(new java.awt.Color(255, 255, 102));
        jButton9.setText("REMOVE FROM BAG");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("GOLD FIT - DOLCE & GABBANA");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(dg)gold fit.jpg"))); // NOI18N
        jLabel15.setText("jLabel2");

        jButton10.setBackground(new java.awt.Color(255, 255, 102));
        jButton10.setText("ADD TO BAG");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("HAND PAINTED - DOLCE & GABBBANA");

        jButton11.setBackground(new java.awt.Color(255, 255, 102));
        jButton11.setText("REMOVE FROM BAG");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 102));
        jButton12.setText("ADD TO BAG");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(dg)hand painted.jpg"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("PRICE : Rs 4,876");

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 51));
        jLabel19.setText("PRICE : Rs 5,632");

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 51));
        jLabel20.setText("RISE JEANS - DOLCE & GABBANA");

        jButton13.setBackground(new java.awt.Color(255, 255, 102));
        jButton13.setText("REMOVE FROM BAG");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)hudson slim fit denim pant.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(dg)rise jeans.jpg"))); // NOI18N
        jLabel22.setText("jLabel2");

        jButton14.setBackground(new java.awt.Color(255, 255, 102));
        jButton14.setText("ADD TO BAG");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 102));
        jButton15.setText("ADD TO BAG");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 51));
        jLabel23.setText("HUDSON SLIM FIT DENIM PANT - TOMMY HILFIGER");

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 51));
        jLabel24.setText("PRICE : Rs 4,708");

        jButton16.setBackground(new java.awt.Color(255, 255, 102));
        jButton16.setText("REMOVE FROM BAG");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 51));
        jLabel25.setText("PRICE : Rs 5,835");

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 51));
        jLabel26.setText("MADISON JEANS - TOMMY HILFIGER");

        jButton17.setBackground(new java.awt.Color(255, 255, 102));
        jButton17.setText("REMOVE FROM BAG");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)mercer denim pant.jpg"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)madison jeans.jpg"))); // NOI18N
        jLabel28.setText("jLabel2");

        jButton18.setBackground(new java.awt.Color(255, 255, 102));
        jButton18.setText("ADD TO BAG");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 255, 102));
        jButton19.setText("ADD TO BAG");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("MERCER DENIM PANT - TOMMY HILFIGER");

        jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 51));
        jLabel30.setText("PRICE : Rs 4,999");

        jButton20.setBackground(new java.awt.Color(255, 255, 102));
        jButton20.setText("REMOVE FROM BAG");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(th)mercer regular fit denim pant.jpg"))); // NOI18N

        jButton21.setBackground(new java.awt.Color(255, 255, 102));
        jButton21.setText("REMOVE FROM BAG");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(255, 255, 102));
        jButton22.setText("ADD TO BAG");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 51));
        jLabel32.setText("PRICE : Rs 6,100");

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 0, 51));
        jLabel33.setText("MERCER REGULAR FIT DENIM PANT - TOMMY HILFIGER");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(79, 79, 79)
                .add(jLabel7)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel21)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jButton15)
                                                .add(51, 51, 51)
                                                .add(jButton13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jLabel19)
                                                .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(12, 12, 12)))
                                .add(222, 222, 222)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 305, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jButton14)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jButton16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18))
                                    .add(jLabel24)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel25)
                                    .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(234, 234, 234)
                                .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 305, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel27)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                .add(jLabel31)
                                                .add(jPanel1Layout.createSequentialGroup()
                                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(jPanel1Layout.createSequentialGroup()
                                                            .add(jButton22)
                                                            .add(51, 51, 51)
                                                            .add(jButton21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .add(jPanel1Layout.createSequentialGroup()
                                                            .add(jLabel32)
                                                            .add(199, 199, 199)))
                                                    .add(12, 12, 12)))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jButton19)
                                                .add(51, 51, 51)
                                                .add(jButton17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(12, 12, 12)))
                                        .add(jLabel33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(222, 222, 222)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel30)
                                        .add(jPanel1Layout.createSequentialGroup()
                                            .add(jButton18)
                                            .add(49, 49, 49)
                                            .add(jButton20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(85, 85, 85)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jButton1)
                                        .add(63, 63, 63)
                                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(44, 44, 44)
                                                .add(jLabel5))
                                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jButton4)
                                        .add(63, 63, 63)
                                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(44, 44, 44)
                                        .add(jLabel6))
                                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel3))))
                        .add(26, 26, 26))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(jLabel17))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jButton6)
                                        .add(63, 63, 63)
                                        .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jButton10)
                                                .add(51, 51, 51)
                                                .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jLabel13)
                                                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(12, 12, 12)))))
                        .add(222, 222, 222)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .add(jButton12)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(26, 26, 26))
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 305, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 356, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(0, 0, Short.MAX_VALUE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel12)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jButton8)
                                    .add(63, 63, 63)
                                    .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel18))))
                .add(52, 52, 52))
            .add(jPanel1Layout.createSequentialGroup()
                .add(70, 70, 70)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 333, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(101, 101, 101)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton1)
                            .add(jButton2)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton4)
                            .add(jButton3))))
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(39, 39, 39)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jLabel7))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton6)
                    .add(jButton5)
                    .add(jButton8)
                    .add(jButton7))
                .add(75, 75, 75)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel16)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(jLabel13))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton10)
                    .add(jButton9)
                    .add(jButton12)
                    .add(jButton11))
                .add(96, 96, 96)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel23)
                    .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel24)
                    .add(jLabel19))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton15)
                    .add(jButton13)
                    .add(jButton14)
                    .add(jButton16))
                .add(46, 46, 46)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel29)
                    .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel30)
                    .add(jLabel25))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton19)
                    .add(jButton17)
                    .add(jButton18)
                    .add(jButton20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 468, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(jLabel33)
                .add(27, 27, 27)
                .add(jLabel32)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton22)
                    .add(jButton21))
                .add(37, 37, 37))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 980, 650);

        jButton23.setBackground(new java.awt.Color(153, 153, 0));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton23.setText("Go To Billing Section");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(830, 20, 180, 50);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)Tornado_Twins.jpg"))); // NOI18N
        jLabel34.setOpaque(true);
        getContentPane().add(jLabel34);
        jLabel34.setBounds(0, 0, 1050, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1056;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1057;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1058;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1059;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1060;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1061;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1062;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1063;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1064;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1065;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        try{ 
        rs = stmt.executeQuery("select * from products where item_code= 1066;");
        while(rs.next()){
            icode = rs.getInt("item_code");
            p = rs.getInt("price");
            bname = rs.getString("brandname");
            iname = rs.getString("item_name");
            t = rs.getString("type");
            s=rs.getInt("stock");
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+s+ "');");
        JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        new OS_Billing_window().setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1056;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1057;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1058;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1059;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1060;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1061;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1062;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1063;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1064;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1065;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill_items where item_code = 1066;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }
        
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Jeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Jeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Jeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Menz_Jeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OS_Menz_Jeans().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
