/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;

/**
 *
 * @author Ashwini K. Singh
 */
public class OS_Womenz extends javax.swing.JFrame {

    /**
     * Creates new form OS_Womenz
     */
    public OS_Womenz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessories = new javax.swing.JButton();
        dresses = new javax.swing.JButton();
        jackets = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accessories.setBackground(new java.awt.Color(175, 12, 93));
        accessories.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        accessories.setText("ACCESSORIES");
        accessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessoriesActionPerformed(evt);
            }
        });
        getContentPane().add(accessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 230, 60));

        dresses.setBackground(new java.awt.Color(175, 12, 93));
        dresses.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        dresses.setText("DRESSES");
        dresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dressesActionPerformed(evt);
            }
        });
        getContentPane().add(dresses, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 240, 60));

        jackets.setBackground(new java.awt.Color(175, 12, 93));
        jackets.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jackets.setText("JACKETS / COATS");
        jackets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacketsActionPerformed(evt);
            }
        });
        getContentPane().add(jackets, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 250, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)images (9).jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 12, 93), 5, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 290, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)images (6).jpg"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 12, 93), 5, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 480));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)images (3).jpg"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 12, 93), 5, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)heart_with_pink_background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoriesActionPerformed
        // TODO add your handling code here:
        new OS_Womenz_Accessories().setVisible(true);
    }//GEN-LAST:event_accessoriesActionPerformed

    private void dressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dressesActionPerformed
        // TODO add your handling code here:
        new OS_Womenz_Dresses().setVisible(true);
    }//GEN-LAST:event_dressesActionPerformed

    private void jacketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacketsActionPerformed
        // TODO add your handling code here:
        new OS_Womenz_Jacket().setVisible(true);
    }//GEN-LAST:event_jacketsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OS_Womenz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessories;
    private javax.swing.JButton dresses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jackets;
    // End of variables declaration//GEN-END:variables
}
