/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.shopping;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashwini K. Singh
 */
public class OS_Womenz_Dresses extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode, p,s;
String bname, iname, t;

    /**
     * Creates new form OS_Women_Dresses
     */
    public OS_Womenz_Dresses() {
        initComponents();
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
        stmt= con.createStatement();
        
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jButton69 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jButton70 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        jButton71 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jButton72 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        jButton73 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jButton74 = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jButton75 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jButton76 = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jButton77 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jButton78 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jButton79 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jButton80 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jButton81 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jButton82 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jButton83 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jButton84 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(fp)Cherry chapstick slip rs4,245.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(fp)Floral mesh lace dress rs6,966.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(fp)lace dream dress rs6,966.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(fp)rose garden dress rs6,966.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(fp)Secret garden shift.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(uo)Metallic pleated dress $89.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(uo)polka dot dress $59.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(uo)sparkle fade knit dress $32.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/Pictures/(uo)sparkle sleeve dress $39.jpg"))); // NOI18N

        jLabel71.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel71.setText("PRICE :  Rs 4,245");

        jLabel52.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("CHERRY CHAPSTICK SLIP - FREE PEOPLE");

        jButton67.setBackground(new java.awt.Color(255, 94, 6));
        jButton67.setText("Add to Bag");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });

        jButton68.setBackground(new java.awt.Color(255, 94, 6));
        jButton68.setText("Remove from Bag");
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel72.setText("PRICE :  Rs 6,966");

        jButton69.setBackground(new java.awt.Color(255, 94, 6));
        jButton69.setText("Add to Bag");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("FLORAL MESH LACE DRESS - FREE PEOPLE");

        jButton70.setBackground(new java.awt.Color(255, 94, 6));
        jButton70.setText("Remove from Bag");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel73.setText("PRICE :  Rs 6,966");

        jButton71.setBackground(new java.awt.Color(255, 94, 6));
        jButton71.setText("Add to Bag");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("LACE DREAM DRESS - FREE PEOPLE");

        jButton72.setBackground(new java.awt.Color(255, 94, 6));
        jButton72.setText("Remove from Bag");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel74.setText("PRICE :  Rs 6,966");

        jButton73.setBackground(new java.awt.Color(255, 94, 6));
        jButton73.setText("Add to Bag");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("ROSE GARDEN DRESS - FREE PEOPLE");

        jButton74.setBackground(new java.awt.Color(255, 94, 6));
        jButton74.setText("Remove from Bag");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel75.setText("PRICE :  Rs 6,966");

        jButton75.setBackground(new java.awt.Color(255, 94, 6));
        jButton75.setText("Add to Bag");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("SECRET GARDEN SHIFT - FREE PEOPLE");

        jButton76.setBackground(new java.awt.Color(255, 94, 6));
        jButton76.setText("Remove from Bag");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel76.setText("PRICE :  Rs 6,966");

        jButton77.setBackground(new java.awt.Color(255, 94, 6));
        jButton77.setText("Add to Bag");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("SPARKLE SLEEVE DRESS - URBAN OUTFITTER");

        jButton78.setBackground(new java.awt.Color(255, 94, 6));
        jButton78.setText("Remove from Bag");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel77.setText("PRICE :  Rs 6,966");

        jButton79.setBackground(new java.awt.Color(255, 94, 6));
        jButton79.setText("Add to Bag");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("POLKA DOT DRESS - URBAN OUTFITTER");

        jButton80.setBackground(new java.awt.Color(255, 94, 6));
        jButton80.setText("Remove from Bag");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel78.setText("PRICE :  Rs 6,966");

        jButton81.setBackground(new java.awt.Color(255, 94, 6));
        jButton81.setText("Add to Bag");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("METALLIC PLEATED DRESS - URBAN OUTFITTER");

        jButton82.setBackground(new java.awt.Color(255, 94, 6));
        jButton82.setText("Remove from Bag");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel79.setText("PRICE :  Rs 6,966");

        jButton83.setBackground(new java.awt.Color(255, 94, 6));
        jButton83.setText("Add to Bag");
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("SPARKLE FADE KNIT DRESS - URBAN OUTFITTER");

        jButton84.setBackground(new java.awt.Color(255, 94, 6));
        jButton84.setText("Remove from Bag");
        jButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton84ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton67)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton73)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton76, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel74)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(247, 247, 247)
                                        .addComponent(jButton81)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(249, 249, 249)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel76)
                                                .addGap(295, 295, 295)
                                                .addComponent(jLabel75))
                                            .addComponent(jButton69)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(212, 212, 212)
                                        .addComponent(jLabel3)
                                        .addGap(191, 191, 191))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)))
                                        .addGap(205, 205, 205)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel73)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton71)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton77)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(379, 379, 379))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(151, 151, 151)
                                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel72))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton79)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel77)
                                        .addGap(349, 349, 349)
                                        .addComponent(jLabel78)))))
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel79))
                            .addComponent(jLabel60)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton83)
                                .addGap(18, 18, 18)
                                .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(819, 819, 819)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton75)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton74, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel71)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton67)
                            .addComponent(jButton68)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel72)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton69)
                            .addComponent(jButton70)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel73)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton71)
                            .addComponent(jButton72))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jLabel76)
                    .addComponent(jLabel75))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton73)
                    .addComponent(jButton76)
                    .addComponent(jButton77)
                    .addComponent(jButton78)
                    .addComponent(jButton75)
                    .addComponent(jButton74))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(jLabel78)
                    .addComponent(jLabel79))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton79)
                    .addComponent(jButton80)
                    .addComponent(jButton81)
                    .addComponent(jButton82)
                    .addComponent(jButton83)
                    .addComponent(jButton84))
                .addGap(82, 82, 82))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1130, 600));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Go To Billing Section");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 230, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/shopping/(img)pink-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1018;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1018;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1019;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1019;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1020;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1020;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1021;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1023;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1023;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1021;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1022;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1022;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1025;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1024;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1026;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton81ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1025;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton82ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from products where item_code= 1024;");
            while(rs.next()){
                icode = rs.getInt("item_code");
                p = rs.getInt("price");
                bname = rs.getString("brandname");
                iname = rs.getString("item_name");
                t = rs.getString("type");
            s = rs.getInt("stock");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}

        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("insert into bill_items values("+icode+", '"+ t +"' , '"+ bname+"','"+ iname + "','"+ p +"','"+ s + "')");
            JOptionPane.showMessageDialog(rootPane,"Added Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/onlineshopping","root","0000");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill_items where item_code = 1026;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane,"Removed Succesfully");
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane,e.getMessage());}
    }//GEN-LAST:event_jButton84ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new OS_Billing_window().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz_Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz_Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz_Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS_Womenz_Dresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OS_Womenz_Dresses().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
